export const ActionTypes = {

    SET_TODAY_WORKOUT: "SET_TODAY_WORKOUT",

    GET_EXERCISES: "GET_EXERCISES",

    SET_DOWNLOAD_PROGRESS: "SET_DOWNLOAD_PROGRESS",
    UPDATE_PRO_DOWNLOAD_STATUS: "UPDATE_PRO_DOWNLOAD_STATUS",

    UPDATE_FAVORITE_WORKOUTS: "UPDATE_FAVORITE_WORKOUTS",

    UPDATE_SELFIES: "UPDATE_SELFIES",

    UPDATE_EQUIPMENTS: "UPDATE_EQUIPMENTS",

    UPDATE_SHUFFLE: "UPDATE_SHUFFLE",

    UPDATE_WORKOUT_TIME: "UPDATE_WORKOUT_TIME",

    UPDATE_PURCHASED_FULL_VERSION: "UPDATE_PURCHASED_FULL_VERSION",

    UPDATE_EAT_ALARMS: "UPDATE_EAT_ALARMS",

    SET_SUBSCRIBE_EMAIL: "SET_SUBSCRIBE_EMAIL",

    GET_YOUTUBE_VIDEOS: "GET_YOUTUBE_VIDEOS",

    SET_COMPLETED_WORKOUT_ID: "SET_COMPLETED_WORKOUT_ID",

    UPDATE_CURRENT_SHUFFLE_ID: "UPDATE_CURRENT_SHUFFLE_ID",
    PREDEFINED_SHUFFLES: "PREDEFINED_SHUFFLES"
}
