export default {
    appName: "6 Pack",
    // Screen Titles
    subscribe: 'Subscribe',
    home: 'Home',
    settings: 'Settings',
    // texts
    email: 'Email',
    newsletter: 'Newsletter',
    feebackSupport: 'Feedback/Support',
    exerciseReminder: 'Exercise Reminder',
    reminderTime:"Reminder Time",
    resetProgram: "Reset Program",
    contactus: 'Contact us',
    reset: 'Reset',
    about: 'About',
    aboutATHLEANX: "About ATHLEANX",
    restore: 'Restore',
    restorePurchases: "Restore Purchases",
    eatAlarm: 'Eat Alarm',
    // Buttons
    rest: 'REST',
    begin: 'Begin',
    done: 'Done',
    save: 'Save',
    privacy: 'Privacy Policy',
    eat: 'Eat',
    train: 'Train',
    learn: 'Learn',
    shuffle: 'Shuffle',
    reShuffle: "Re-Shuffle",
    equipment: 'Equipment',
    favorites: 'Favorites',
    selfies: "Selfies",
    cancel: 'Cancel',
    search: 'Search',
    moreVideos: "More Videos",
    brag: "brag",
    yes: 'Yes',
    no: 'No',
    learnMore: 'Learn More',
    restday: "Rest Day",
    addMusic: "Add Music!",
    ok: "OK",
    finished: "FINISHED!",
    next: 'Next',
    suffle: 'Suffle',
    purchase: 'Purchase',


    // Long texts
    todayWorkout: "Today's Workout",
    workoutTitle: 'When do you workout?',
    workoutNote: 'Please select a time of the day that we can remind you!',
    whyStop: 'Why Stop at Abs?',
    enterYour: "Enter your gmail to get this free bonus and get Jeff Cavaliere\'s hand selected favorite workout in the 6 Pack Promise.",
    alreadySubscribed: "I am already subscribed",
    totalWorkout: 'Total Workout Time:',
    startWorkout: 'Start Workout',
    endWorkout: 'End Workout',
    checkoutMoreVideos: 'Check out more videos on our channel',
    shuffleWorkout: 'Shuffle Workout',
    notFavorites: 'No Favorites Found',
    confirmDeleteSelfie: "Are you sure you want to delete this selfie?",
    notSelfiesFound: "No Selfies Found",
    mealReminder: "Meal and Snack Reminder",
    chooseReminder: "Choose your reminder times and types!",
    axSuppelement: "AX Supplement Reminder",
    upgradeToPro: "Upgrade to Pro!",
    upgradeToProEnjoy: "Upgrade to Pro to enjoy all features of the 6 Pack Promise",
    areYouSureYouWantToMove: (week, day) => `Are you sure you want to move to Week ${week}, Day ${day} in your workout program?`,
    downloadingExercises: 'Downloading Exericises',
    downloadingDescription: "We are downloading all 6 Pack Promise Exercises to your device.",
    workoutToYourFavoriteSongs: "Workout to your favorite songs by running your perferrend music player simultaneously.",
    yourProgressHas: "Your progress has been logged!",
    workoutFavorited: "Workout Favorited",
    favoriteThisWorkout: "Favorite this workout",
    pleaseEnterEmail: "Please enter your email address!",
    pleaseEnterValidEmail: "Please enter valid email address!",
    athleanRxSupplements: 'ATHLEAN-RX Supplements',
    selectYourEquipment: "Select Your Equipment",
    bodyweightAlways: "Bodyweight is always selected",
    chooseYourFintess: "Choose your fitness level:",
    sorry: "Sorry!",
    youDonthaveSelfie: "You don't have selfie to share. Please add new selfie",
    shareDescription: "Check out my progress with AthleanX Six Pack Promise!",
    appShareDescription: "I just completed a workout with the 6-Pack Promise app",
    pleaseConfirmThatYouWant: "Please confirm that you want to reset your progress and start the program again from Day 1",
    areYouSureYoucannot: "Are you sure? You cannot undo resetting the progream",
    reviewTheApp: "Review the App",
    motivateOthers: "Motivate Others!",
    ifYouHaveKindWords: "If you have kind words to say, please tap the button:\n\nA sentence or two about your positive experience encourages others to get that 6 pack!"
}