require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SixPackPromise' do

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Microphone', :modular_headers => true, :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Camera', :modular_headers => true,:path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary',  :modular_headers => true, :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'XCDYouTubeKit', '~> 2.15.0'
  pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'
  pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'SixPackPromiseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SixPackPromise-tvOS' do
  # Pods for SixPackPromise-tvOS

  target 'SixPackPromise-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
